# Generated by Django 5.2.1 on 2025-06-02 03:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hewan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
                ('jenis', models.CharField(choices=[('kucing', 'Kucing'), ('anjing', 'Anjing')], max_length=10)),
                ('umur', models.PositiveIntegerField(help_text='Umur dalam bulan')),
                ('deskripsi', models.TextField()),
                ('foto', models.ImageField(upload_to='foto_hewan/')),
                ('status', models.CharField(default='Tersedia', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='PengajuanAdopsi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_pengaju', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('alasan', models.TextField()),
                ('tanggal_pengajuan', models.DateTimeField(auto_now_add=True)),
                ('hewan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adopsi.hewan')),
            ],
        ),
    ]
