# Generated by Django 5.2.1 on 2025-06-02 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adopsi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pengajuanadopsi',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Diterima', 'Diterima'), ('Ditolak', 'Ditolak')], default='Pending', max_length=10),
        ),
    ]
