# Generated by Django 5.2.1 on 2025-06-03 22:03

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adopsi', '0002_pengajuanadopsi_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hewan',
            options={'ordering': ['-tanggal_dibuat'], 'verbose_name': 'Hewan', 'verbose_name_plural': 'Hewan'},
        ),
        migrations.AlterModelOptions(
            name='pengajuanadopsi',
            options={'ordering': ['-tanggal_pengajuan'], 'verbose_name': 'Pengajuan Adopsi', 'verbose_name_plural': 'Pengajuan Adopsi'},
        ),
        migrations.AddField(
            model_name='hewan',
            name='tanggal_dibuat',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hewan',
            name='tanggal_diupdate',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='pengajuanadopsi',
            name='catatan_admin',
            field=models.TextField(blank=True, help_text='Catatan dari admin', null=True),
        ),
        migrations.AlterField(
            model_name='hewan',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='foto_hewan/'),
        ),
        migrations.AlterField(
            model_name='hewan',
            name='status',
            field=models.CharField(choices=[('Tersedia', 'Tersedia'), ('Diproses', 'Diproses'), ('Diadopsi', 'Diadopsi')], default='Tersedia', max_length=20),
        ),
        migrations.AlterField(
            model_name='hewan',
            name='umur',
            field=models.PositiveIntegerField(help_text='Umur dalam bulan', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(300)]),
        ),
        migrations.AlterField(
            model_name='pengajuanadopsi',
            name='hewan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pengajuan_adopsi', to='adopsi.hewan'),
        ),
    ]
